on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

name: Deploy to Cloudfront distribution Develop

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn install
      
      - name: Multiples
        uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: .env.devel

      - name: Get frontend version
        run: echo "VERSION=$(cat package.json | jq '.version' | sed "s/\"//g" >> $GITHUB_ENV
      
      - name: Check version
        run: echo $VERSION

      - name: print 1 method
        run: echo $PRIMERO es el primero
      
      - name: print 2 method
        run: echo $SEGUNDO
      
      - name: print finales
        run: echo $TEST_NO_NEWLINE


