on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

name: Deploy to Cloudfront distribution Develop

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn install

      - name: set variables
        run: echo "SEGUNDO=segundo" >> $GITHUB_ENV

      - name: set old method
        run: echo $PRIMERO old method
        env:
          PRIMERO: "daniel"

      - name: Install jq
        run: sudo apt-get install jq

      - name: Get frontend version
        run: echo "VERSION=$(cat package.json | jq '.version' | sed "s/\"//g")" >> $GITHUB_ENV

      - name: Check build
        run: ls -la

      - name: print 1 method
        run: echo $PRIMERO
      
      - name: print 2 method
        run: echo $SEGUNDO


